export type sizingScale = 'xs' | 'sm' | 'md' | 'lg' | 'xl' | 'full' | 'auto';
export type colorRange =
  | 'primary'
  | 'secondary'
  | 'success'
  | 'warning'
  | 'alert'
  | 'gray'
  | 'orange'
  | 'violet'
  | 'slate'
  | 'red'
  | 'blue'
  | 'green'
  | 'yellow'