import { IconWarning } from '@/core/assets/icons/icons'
import Button from '@/core/components/atoms/form/Button/Button'
import Navigation from '@/core/components/molecules/navigation/Navigation'
import Header from '@/core/components/organisms/Header/Header'
import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        style={{
          display: 'flex',
          flexDirection: 'column',
          gap: '2rem',
          flexWrap: 'wrap',
        }}
      >
        <Header>
          <Navigation></Navigation>
        </Header>

        <div
          style={{
            display: 'flex',
            flexWrap: 'wrap',
            flexDirection: 'column',
            alignItems: 'center',
            margin: '1rem 1rem',
            gap: '1rem',
          }}
        >
          {/* <Button radius="md" type="submit">
            Button extra small
          </Button>
          <Button radius="full" type="submit" icon={<IconWarning />}>
            Button extra small avec une icône à gauche
          </Button>
          <Button radius="md" type="submit" iconRight={<IconWarning />}>
            Button extra small avec une icône à droite
          </Button>
          <Button size="sm" radius="md" type="submit">
            Button small
          </Button>
          <Button size="sm" radius="md" type="submit" icon={<IconWarning />}>
            Button small avec un icône à gauche
          </Button>
          <Button
            size="sm"
            radius="md"
            type="submit"
            iconRight={<IconWarning />}
          >
            Button small avec un icône à droite
          </Button>
          <Button size="md" radius="md" type="submit">
            Button medium
          </Button>
          <Button size="md" radius="md" type="submit" icon={<IconWarning />}>
            Button medium avec un icone à gauche
          </Button>
          <Button
            color="secondary"
            size="md"
            radius="md"
            type="submit"
            iconRight={<IconWarning />}
          >
            Button medium avec un icone à droite
          </Button>
          <Button size="lg" radius="md" type="submit">
            Button large
          </Button>

          <Button size="lg" radius="md" type="submit" icon={<IconWarning />}>
            Button large avec un icone à gauche
          </Button>

          <Button
            size="lg"
            radius="md"
            type="submit"
            iconRight={<IconWarning />}
          >
            Button large avec un icone à droite
          </Button> */}

          <Button size="xl" radius="md" type="submit" shadow bordered>
            Button extra large borderd
          </Button>

          <Button
            color="secondary"
            size="xl"
            radius="full"
            type="submit"
            icon={<IconWarning />}
          >
            Button extra large
          </Button>

          <Button
            color="alert"
            size="xl"
            radius="md"
            type="submit"
            flat
            iconRight={<IconWarning />}
            bordered
            shadow
          >
            Button extra large
          </Button>

          <Button
            color="alert"
            size="xl"
            radius="md"
            type="submit"
            flat
            iconRight={<IconWarning />}
            light
          >
            Button extra large
          </Button>

          <Button
            color="warning"
            size="xl"
            radius="md"
            type="submit"
            flat
            iconRight={<IconWarning />}
          ></Button>
          <Button
            color="warning"
            size="lg"
            radius="md"
            type="submit"
            iconRight={<IconWarning />}
            disabled
          >
            Disabled{' '}
          </Button>
        </div>
      </main>
    </>
  )
}
